# Generated by Django 4.1.5 on 2023-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_remove_galleryimage_title_alter_galleryimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='blur',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
